# Generated by Django 4.2 on 2023-06-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0004_alter_ticket_nickname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="nickname",
            new_name="writer",
        ),
    ]
