# Generated by Django 4.2 on 2023-06-21 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainpage", "0005_rename_nickname_ticket_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
