# Generated by Django 4.2 on 2023-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0007_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="pub_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="pub_date",
            field=models.DateField(),
        ),
    ]
