# Generated by Django 4.2 on 2023-06-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0008_alter_comment_pub_date_alter_ticket_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="pub_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="pub_date",
            field=models.DateTimeField(),
        ),
    ]
