# Generated by Django 4.2 on 2023-06-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0010_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="report_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
