# Generated by Django 4.2.1 on 2023-06-22 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qnapage', '0003_rename_contenct_qnacomment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnacomment',
            name='comment_like',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qnacomment',
            name='commnet_like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
