# Generated by Django 4.2.1 on 2023-06-22 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qnapage', '0004_qnacomment_comment_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnacomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='qnapage.qnacomment'),
        ),
    ]
