# Generated by Django 4.2.1 on 2023-06-22 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnapage', '0005_alter_qnacomment_parent_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qnacomment',
            old_name='commnet_like_count',
            new_name='comment_like_count',
        ),
    ]
