# Generated by Django 4.2 on 2023-06-23 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qnapage", "0006_rename_commnet_like_count_qnacomment_comment_like_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qnacomment",
            name="parent_comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qnapage.qnacomment",
            ),
        ),
        migrations.AlterModelTable(
            name="qnacomment",
            table="comments",
        ),
    ]
