# Generated by Django 4.2 on 2023-06-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qnapage", "0007_alter_qnacomment_parent_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qnacomment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply",
                to="qnapage.qnacomment",
            ),
        ),
        migrations.AlterModelTable(
            name="qnacomment",
            table=None,
        ),
    ]
