# Generated by Django 4.2 on 2023-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qnapage", "0008_alter_qnacomment_parent_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qna",
            name="pub_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="qnacomment",
            name="pub_date",
            field=models.DateField(),
        ),
    ]
