# Generated by Django 4.2 on 2023-06-25 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qnapage', '0011_alter_qna_pub_date_alter_qnacomment_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnareply',
            name='reply_like',
            field=models.ManyToManyField(blank=True, related_name='reply_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qnareply',
            name='reply_like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
