# Generated by Django 4.2 on 2023-06-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qnapage", "0012_qnareply_reply_like_qnareply_reply_like_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="qnacomment",
            name="report_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
