# Generated by Django 4.2 on 2023-06-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qnapage", "0013_qnacomment_report_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="qnacomment",
            old_name="report_count",
            new_name="comment_report_count",
        ),
        migrations.AddField(
            model_name="qnareply",
            name="reply_report_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
